Pipeline runs
valohai/valohai-cli pull request #126
Opened 2020-08-28 12:27 UTC by magdapoppins

2020-08-31 08:14 UTC, akx requested changes

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/__init__.py
> +    Execution-related commands.
```suggestion
    Pipeline-related commands.
```

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +@click.option('--image', '-i', default=None, help='Override the Docker image specified in the step.')
This seems extraneous?

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +        error('Pipeline could not be created. Check the config of your valohai.yaml -file.')
Hmm, shouldn't this also _show_ the error that occurs somehow, not just say ":shrug: an error occurred"?

(In fact, I think it might better to not wrap this in a try-except at all. The exception that's raised should be descriptive enough...)

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +            "image": config.steps.get(node.step).image,
DRY out the repetition of `config.steps.get(node.step)`, please (use the Extract Variable refactoring in PyCharm).

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +    for node in pipeline.nodes:
I'd refactor the body of this loop into a function of its own (`build_node`).

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +            "time_limit": 0,
AFAICR this is optional, so don't pass it...

```suggestion
```

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +    return list(config.pipelines.keys())[0]
Can you explain what's going on here?

2020-08-31 08:14 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +        "title": pipeline.name,
Could this maybe be an optional parameter you can pass? :)

2020-08-31 08:32 UTC, magdapoppins commented on valohai_cli/commands/pipeline/run/utils.py
> +    return list(config.pipelines.keys())[0]
"If nothing matching the title is found, just start the first one" 😅 I am open for embettering this still. Will do.

2020-08-31 08:58 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +    return list(config.pipelines.keys())[0]
I don't think that's a good idea. You could look at how step names are resolved in the execution run thing; it will use the first non-ambiguous prefix, but never default to "just run something yo".

2020-08-31 11:04 UTC, magdapoppins commented on valohai_cli/commands/pipeline/run/utils.py
> +    return list(config.pipelines.keys())[0]
Updated this so it works like execution matching.

2020-08-31 11:22 UTC, akx requested changes
Could you also add a test?

2020-08-31 11:22 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +def start_pipeline(config, pipeline, project_id, commit, optional_title):
```suggestion
def start_pipeline(config, pipeline, project_id, commit, title=None):
```

2020-08-31 11:22 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +        "title": optional_title or pipeline.name,
```suggestion
        "title": title or pipeline.name,
```

2020-08-31 11:22 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +    success('Pipeline #{} queued. See {}'.format(resp.get("counter"), resp.get("urls").get("display")))
The marker character for pipelines is `=`:

```suggestion
    success('Pipeline ={} queued. See {}'.format(resp.get("counter"), resp.get("urls").get("display")))
```

2020-08-31 11:22 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +            '"{pipeline}" is ambiguous.\nIt matches {matches}.\nKnown steps are {steps}.'.format(
What's this about `steps` here?
```suggestion
            '"{pipeline}" is ambiguous.\nIt matches {matches}.\nKnown pipelines are {pipelines}.'.format(
```

2020-09-01 11:35 UTC, akx requested changes

2020-09-01 11:35 UTC, akx commented on tests/commands/execution/run_test_utils.py
> +        return EXECUTION_DATA.copy()
The pipeline create response probably isn't an execution create response...

2020-09-01 11:35 UTC, akx commented on tests/commands/pipeline/test_run.py
> +        yaml_fp.write('''
I think this data could live in `tests/fixture_data.py`?

2020-09-01 11:35 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +@click.option('--title', '-c', default=None, metavar='SHA', help='The optional title of the pipeline run.')
Metavar is not SHA here; leave it out :)
```suggestion
@click.option('--title', '-c', default=None, help='The optional title of the pipeline run.')
```

2020-09-01 11:35 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +        "title": title if title else pipeline.name,
```suggestion
        "title": title or pipeline.name,
```

2020-09-03 11:04 UTC, akx requested changes
The return data fixture could use the execution and project data we already have, for DRYing (even if it's not exactly a 100% match to what the API would actually return).

We're getting there 💪

2020-09-03 11:04 UTC, akx commented on tests/fixture_data.py
> +                         'display_repository': 'http://127.0.0.1:8000/p/magda/tensorflow-example/settings/repository/'}},
```suggestion
    'project': PROJECT_DATA,
```

2020-09-03 11:04 UTC, akx commented on tests/fixture_data.py
> +                                 'stop': 'http://127.0.0.1:8000/api/v0/executions/01744e18-c946-53e7-5780-03267649539d/stop/'}},
```suggestion
              {'execution': EXECUTION_DATA,
```

2020-09-03 11:04 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +
Seems unused?
```suggestion
```

2020-09-03 11:04 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +from click import BadParameter
```suggestion
```

2020-09-03 11:14 UTC, magdapoppins commented on valohai_cli/commands/pipeline/run/utils.py
> +        raise BadParameter(
If you make me do this change I will do it in `executions/run/utils.py` and `models/project.py` as well for consistency.

2020-09-03 11:15 UTC, akx commented on valohai_cli/commands/pipeline/run/utils.py
> +        raise BadParameter(
Sure. I think a single `import click` is better than `import click; from click import ...` :)

2020-09-07 07:27 UTC, akx approved these changes

2020-09-07 07:27 UTC, merged