(WIP) New `vh yaml` command to generate/update configs based on .py source
valohai/valohai-cli pull request #131
Opened 2020-11-12 10:22 UTC by JuhaKiili

Review, but don't merge yet!

2021-01-05 12:17 UTC, akx requested changes
Sorry for the super late review 😞

2021-01-05 12:17 UTC, akx commented on valohai_cli/commands/yaml.py
> +def yaml(filenames):
I wonder if the name here is a little loaded? Maybe make `vh yaml` a group for future expansion, and turn this into `vh yaml generate`?

2021-01-05 12:17 UTC, akx commented on valohai_cli/commands/yaml.py
> +            'Missing path(s) to source Python file(s). Example: vh yaml hello.py')
You should be able to do this in the `argument` itself (`required=True` or similar)?

2021-01-05 12:17 UTC, akx commented on valohai_cli/commands/yaml.py
> +    directory = (project.directory if project else get_project_directory())
Would just `directory = get_project_directory()` do? I didn't check the implementation so not sure.

2021-01-05 12:17 UTC, akx commented on valohai_cli/commands/yaml.py
> +    return None
I would imagine this utility exists in valohai-cli already...

2021-01-05 12:17 UTC, akx commented on valohai_cli/commands/yaml.py
> +            info("valohai.yaml already up-to-date.")
Won't this just happily overwrite `config_path` for each `source_path`?

2021-01-28 13:06 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +    directory = (project.directory if project else get_project_directory())
For example `vh lint` uses the same pattern that I'm doing here. https://github.com/valohai/valohai-cli/blob/988c7a2b415ad244379ce8af4e4ca0ff74ea5b36/valohai_cli/commands/lint.py#L47

`get_project_directory()` has simpler logic than `get_project().directory`. To be honest, I don't quite understand why there are these two ways, but I took the `vh lint` as the ground truth as it is trying to find the correct `valohai.yaml` just like my command.

2021-01-28 13:40 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +    directory = (project.directory if project else get_project_directory())
Edit: I refactored the code so that I'm using the Project object and don't need this code anymore

2021-01-28 13:43 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +            info("valohai.yaml already up-to-date.")
No. For each `source_path` the same `valohai.yaml` is updated, **not** overwritten.

If you feed this command multiple `source_path`, each will contain a different Valohai step, and updates a different part of the config file.

2021-01-28 13:44 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +            'Missing path(s) to source Python file(s). Example: vh yaml hello.py')
Pushed fix

2021-01-28 13:45 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +def yaml(filenames):
Changed to `vh yaml step foobar.py`

The reasoning is that we only generate/update single step here. We might have things like `vh yaml endpoint` or `vh yaml pipeline`.

2021-01-28 13:46 UTC, JuhaKiili commented on valohai_cli/commands/yaml.py
> +    return None
Pushed fix

2021-01-29 12:44 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +def get_updated_config(source_path: str, project: Project) -> (Config, Config):
Shouldn't the rtype be

```suggestion
def get_updated_config(source_path: str, project: Project) -> Config:
```

2021-01-29 12:44 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +def update_yaml_from_source(source_path: str, project: Project):
Wouldn't hurt to return a "did something" flag from here :)
```suggestion
def update_yaml_from_source(source_path: str, project: Project) -> bool:
```

2021-01-29 12:44 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +
```suggestion
            out_file.write(config_to_yaml(new_config))
        return True
    return False
```

2021-01-29 12:44 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +def yaml_needs_update(source_path: str, project: Project):
```suggestion
def yaml_needs_update(source_path: str, project: Project) -> bool:
```

2021-01-29 12:44 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +    return project.get_config() if os.path.isfile(project.get_config_filename()) else None
Wonder if this'd be better phrased as

```suggestion
def get_current_config(project: Project) -> Optional[Config]:
    try:
        return project.get_config()
    except FileNotFoundError:
        return None
```

2021-03-01 14:20 UTC, akx approved these changes
🚢

2021-03-01 14:22 UTC, merged