Add vh yaml pipeline command
valohai/valohai-cli pull request #142
Opened 2021-04-14 09:21 UTC by JuhaKiili

Allow users to create/update a pipeline in their `valohai.yaml`, using the following command:

`vh yaml pipeline mypipeline.py`

The actual logic for getting the Pipeline config is not here, but in `valohai.internals.pipeline.get_pipeline_from_source()`.

2021-04-22 10:58 UTC, akx requested changes

2021-04-22 10:58 UTC, akx commented on setup.py
> +        'valohai-utils>=0.1.7',
The highest version of `valohai-utils` on https://github.com/valohai/valohai-utils/tree/699d352a39251ddc4b195e039ae807a1ccdba740 is `0.1.6`. Did you forget to push 0.1.7 to git, or are there other shenanigans going on here?

2021-04-22 12:00 UTC, JuhaKiili commented on setup.py
> +        'valohai-utils>=0.1.7',
My bad. Forgot to push indeed.

2021-04-23 06:36 UTC, akx approved these changes

2021-04-23 06:36 UTC, merged