Embetter login host prompt flow
valohai/valohai-cli pull request #152
Opened 2021-06-09 13:57 UTC by akx

With this PR:

* login will ask to verify the login host; one can just hit ENTER to accept the default (app.valohai.com, or whatever had been overridden using the `VALOHAI_HOST` envvar)
* login will not fail if the host (either via arg or interactive prompt) is malformed (not a real base URL)

Fixes #151

# What does it look like?

## default interactive flow + validation

<img width="881" alt="Screenshot 2021-06-09 at 16 55 01" src="https://user-images.githubusercontent.com/58669/121368193-8e295f80-c943-11eb-8338-2de0811a6936.png">

## host defined on command line

<img width="602" alt="Screenshot 2021-06-09 at 16 55 29" src="https://user-images.githubusercontent.com/58669/121368182-8bc70580-c943-11eb-96f3-e7a722f1a326.png">

2021-06-09 23:30 UTC, ruksi requested changes
improving the login flow to be more intuitive

lgtm

`mypy` says nono on some type hints though

2021-06-10 12:17 UTC, tokkoro commented
Does this login me into myhai.com?
`vh --valohai-host https://myhai.com/ login`

2021-06-10 12:18 UTC, akx commented
> Does this login me into myhai.com?
> `vh --valohai-host https://myhai.com/ login`

Yes, it asks you whether to log in on https://myhai.com/ or whether to override it.

2021-06-10 12:18 UTC, tokkoro commented
:+1: super

2021-06-10 12:23 UTC, tokkoro approved these changes
I'm not totally sure why an user would need to type https:// in front of host name, it could be a default and can be overwritten with http:// if explicitly typed. That would be more :potato:proof.

2021-06-10 12:23 UTC, akx commented
> `mypy` says nono on some type hints though

Mypy is calm now.

2021-06-14 09:15 UTC, ruksi approved these changes
lgtm

> I'm not totally sure why an user would need to type https:// in front of host name, it could be a default and can be overwritten with http:// if explicitly typed. That would be more proof.

yeah, could be a nice addition, I have nothing against that

I think this is a good first version as is and that could be added later?

2021-06-14 11:24 UTC, merged