Notify the user if a project is missing in vh yaml
valohai/valohai-cli pull request #165
Opened 2021-09-16 11:33 UTC by magdapoppins

Fixes valohai/valohai-utils#64

2021-09-16 11:53 UTC, akx reviewed
What is the assertion error thrown by valohai_utils? Could we fix the command to work without a project? I see no reason why YAML generation would require a linked project.

2021-09-21 06:47 UTC, magdapoppins commented
> What is the assertion error thrown by valohai_utils? Could we fix the command to work without a project? I see no reason why YAML generation would require a linked project.

Requires some decoupling, but should be doable!

2021-09-22 06:38 UTC, akx requested changes

2021-09-22 06:38 UTC, akx commented on valohai_cli/commands/yaml/step.py
> +        info("no project linked - assuming files are in current directory.")
Can you try if this works with just

```suggestion
    if project is None:
        info("no project linked - assuming files are in current directory.")
        project = Project(data={}, directory=os.getcwd())
```

i.e. you simulate a project that would live in this directory?

That way you don't need to change everything to accept no Project.

2021-09-22 10:16 UTC, akx approved these changes
Nice and clean 😁

2021-09-22 10:16 UTC, merged