Allow creating adhoc commits with a nonstandard yaml path
valohai/valohai-cli pull request #192
Opened 2022-05-03 12:00 UTC by magdapoppins

WIP 

Fixes valohai/roi#3953

2022-05-04 07:54 UTC, akx requested changes
Beside the inline comments... I think we'd need to post the YAML path with the adhoc upload endpoint?

2022-05-04 07:54 UTC, akx commented on valohai_cli/commands/project/link.py
> +    projects: List[dict] = request('get', '/api/v0/projects/', params={'limit': '1000', 'include': 'yaml_path'}).json()['results']
Hmm... this will not pick up changes to the yaml path that are done after linking the project. :(

May need to discuss how to best do this in meatspace :)

2022-05-04 07:54 UTC, akx commented on valohai_cli/commands/lint.py
> +        config_file = os.path.join(directory, project.data.get('yaml_path', 'valohai.yaml') if project else 'valohai.yaml')
Maybe the `project.data.get('yaml_path', 'valohai.yaml') if project else 'valohai.yaml'` expression should be broken out to a separate line for clarity?

Also, I suppose it should use `project.get_config_filename()`?

2022-05-04 07:54 UTC, akx commented on valohai_cli/models/project.py
> +        filename = self.data['yaml_path'] if self.data.get('yaml_path') else 'valohai.yaml'
```suggestion
        filename = self.data.get('yaml_path') or 'valohai.yaml'
```

2022-05-16 07:06 UTC, akx requested changes

2022-05-16 07:06 UTC, akx commented on valohai_cli/models/project.py
> +        return os.path.join(self.directory, yaml_path)
Hmm... I'm not sure it's a good idea that we implicitly do a request every time `get_config_filename` is called.

Since we do cache some project info locally anyway, what if...

* add a `refresh_details()` function that we call at the start of `run` or `lint`
* it saves the project detail information in the local persistence
* a `Project.get_yaml_path()` function gets the yaml path from the local persistence
* this would use that (unless the YAML path is explicitly overridden for e.g. adhoc runs)

?

2022-05-18 07:37 UTC, akx commented on valohai_cli/packager.py
> +        raise ConfigurationError(f'valohai.yaml missing from {directory}')
Should this message also refer to the YAML path specified?

2022-05-18 07:38 UTC, akx commented on valohai_cli/models/project.py
> +        self.data.update(data)
For prettiness's sake, maybe this function shouldn't be sandwiched between the two related `get_*` functions, but somewhere else in the class?

2022-05-18 07:39 UTC, akx commented on valohai_cli/commands/lint.py
> +        yaml_path = project.get_yaml_path() if project else 'valohai.yaml'
```suggestion
        if project:
            project.refresh_details()
            yaml_path = project.get_yaml_path()
        else:
            yaml_path = 'valohai.yaml'
```

2022-05-18 07:40 UTC, akx commented on valohai_cli/commands/execution/run/frontend_command.py
> +    project.refresh_details()
Somewhat unrelated to this line, but didn't we talk about the run command (especially in adhoc mode) to be able to accept a YAML path argument? Should that be in this PR, or would it be in a forthcoming one?

2022-05-18 07:47 UTC, magdapoppins commented on valohai_cli/commands/execution/run/frontend_command.py
> +    project.refresh_details()
Broke this into #193 ✅

2022-05-19 08:40 UTC, merged