Add data and alias command to fetch Datums and Datum Aliases
valohai/valohai-cli pull request #200
Opened 2022-06-20 07:49 UTC by tokkoro

# Valohai-cli Data

## Data
In a linked project directory, you can read datums using `vh data list` or from specific project by `vh --project <project-id> data list`

**Columns**
* Name: The name of a datum 
* Size: The file size of a datum
* Output of Exec: The execution that a datum came from
* Created At: The time when a datum was created
* URL: datum:// url to use as an input for execution for example
* URI: Storage uri for the file that a datum is pointing.

### Example output
```text
Name                        Size     Output of Exec  Created At                   URL                                           URI                                                                                    
--------------------------  -------  --------------  ---------------------------  --------------------------------------------  ----------------------------------------------------------
sweed_music_of_birds.wav     9.0 MB  Not from exec   2022-05-19T07:46:31.696250Z  datum://0180db51-7a50-679f-d635-cafb925c2122  s3://bucket/data/PATH/upload/sweed_music_of_birds.wav
small_data_file_ouput.txt   18.0  B  #756            2022-05-15T11:12:35.408585Z  datum://0180c735-8630-9812-b08e-cf1f2556d10c  s3://bucket/data/PATH/output-756/small_data_file_ouput.txt        
output_file.txt             18.0  B  #752            2022-05-14T10:13:26.512045Z  datum://0180c735-636f-a104-33b4-1972a83a492b  s3://bucket/data/PATH/output-752/output_file.txt
```

## Alias
In a linked project directory, you can read datum aliases using `vh alias list` or from specific project by `vh --project <project-id> alias list`

**Columns**
* Name: The name of an alias 
* Datum: The name of the datum that an alias is pointing to.
* Last Modified: The time an alias was previously updated
* URL: datum:// url to use as an input for execution for example
### Example output
```text
Name     Datum                Last Modified                URL            
-------  -------------------  ---------------------------  ---------------
most-ac  layer-0-weights.csv  2022-06-17T10:22:40.679929Z  datum://most-ac
alias-1  layer-1-biases.csv   2022-06-17T10:22:31.754594Z  datum://alias-1
the-eht  layer-1-biases.csv   2022-06-17T10:22:24.286183Z  datum://the-eht
alias-0  layer-0-weights.csv  2022-06-17T10:21:09.323021Z  datum://alias-0

```

2022-06-20 13:13 UTC, ruksi requested changes
let's huddle on this this week :+1:

2022-06-20 13:13 UTC, ruksi commented on valohai_cli/commands/alias/list.py
> +    """
a list of datum aliases? probably a copy-paste error

2022-06-20 13:13 UTC, ruksi commented on valohai_cli/commands/data/__init__.py
> +    """
slightly off-put but mixing three terms: `data`, `datums` and `datum`

there should just be two terms; singular and plural
* `datum` & `datums`
* `datum` & `data`

so the `data` is only the customer facing term here? should this be reflected e.g. in the documentation and the web app guide texts?

not a major issue but it makes even the reviewing slightly more troublesome, I can imagine it can make the usage without code completion even more annoying

maybe we should give this a minor discussion during next daily, but not a blocking issue if the change is otherwise deemed essential

2022-06-22 07:32 UTC, tokkoro commented on valohai_cli/commands/data/__init__.py
> +    """
I fixed this so that the user interface is always talking about **data**. Most of the code is also, but for example test data is named as custom in `fixture_data.py`.

2022-06-23 06:18 UTC, ruksi approved these changes
lgtm!

`convert_size` could be moved into some utility directory for reuse, but this can be done later if the size conversions are needed later (moving it now could improve discoverability)

there could be more options for the `list` commands like customizing sort etc. but this is an excellent first version

2022-06-23 06:36 UTC, merged