Deployment version creation
valohai/valohai-cli pull request #206
Opened 2022-07-18 12:15 UTC by magdapoppins

Fixes #185

2022-07-21 11:22 UTC, akx requested changes
Tests missing, too.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        ))
I didn't know we have parameters for deployment versions? 🙃

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        endpoints = [e['endpoint'] for e in commit_config['config'] if e.get('endpoint')]
You should probably use `valohai_yaml.parse(...)` to get a real Config object instead of dealing with nested dicts.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        # options, parameters, inputs = self._sift_kwargs(kwargs)
dead code?

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                'files': {},
I'd either fill this up here, or clarify in a comment that the next loop will deal with it.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        ))
Prefer f-strings.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                    datum_id = value[8:] if DATUM_URI_PREFIX in value else value
8 smells like a magic constant.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                    endpoint_configurations[designated_endpoint]['files'][filename] = datum_id
Would be a good idea to validate that the ID is an UUID.

2022-07-21 11:22 UTC, akx commented on valohai_cli/commands/deployment/create_version/excs.py
> +        return []
What's the point here? This always returns `[]`.

2022-07-21 11:22 UTC, akx commented on valohai_cli/exceptions.py
> +
What's the point in moving this function?

2022-08-01 10:35 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        deployment: dict[str, Any],
This type annotation is not compatible with Python 3.8 and older.

2022-08-05 06:56 UTC, akx requested changes

2022-08-05 06:56 UTC, akx commented on tests/fixture_data.py
> +DEPLOYMENT_VERSION_DATA = {
Could you change this to not contain actual live data?

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        suggested_version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
Might be nice to print out the autogenerated version name.

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        suggested_version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
```suggestion
        version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
```

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        version_name=version_name if version_name else suggested_version_name,
```suggestion
        version_name=version_name,
```

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +    A dynamically-generated subcommand that has Click options for inputs.
They're not strictly speaking inputs for deployments...

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +            url=f'/api/v0/commits/{commit}',
```suggestion
            url=f'/api/v0/commits/{commit}/',
```

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +            help=f'Input "{humanize_identifier(name)}"',
```suggestion
            help=f'File "{humanize_identifier(name)}"',
```

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        option.help_group = 'Input Options'  # type: ignore[attr-defined]
```suggestion
        option.help_group = 'File Options'  # type: ignore[attr-defined]
```

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +            'inherit_environment_variables': False,  # TODO is this a sane default?
It's not really a "default" if you can't change it at all. Maybe surface it as an option?

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/excs.py
> +        return []
You don't need this at all. The execution creation stuff had its own API error class so it could show a relevant hint, but since you're not doing that, there's no need for an error class.

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        for e in self.endpoints:
By the looks of it, `self.endpoints` isn't validated against the commit configuration... Would probably be good to guard against typos?

2022-08-05 06:56 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                'replicas': 1,
This is missing support for
```
'cpu_request',
'memory_request',
'memory_limit',
'node_selector',
```
but maybe those can be added later.

2022-08-05 07:53 UTC, magdapoppins commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        version_name=version_name if version_name else suggested_version_name,
Mypy doesn't want it this way 
`valohai_cli/commands/deployment/create_version/create_version.py:54: error: Name "version_name" already defined on line 24  [no-redef]`

2022-08-05 07:53 UTC, magdapoppins commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        suggested_version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
Mypy doesn't want it this way 
`valohai_cli/commands/deployment/create_version/create_version.py:54: error: Name "version_name" already defined on line 24  [no-redef]`

2022-08-05 08:27 UTC, akx requested changes
There are still old outstanding comments in addition to these 3 new ones.

2022-08-05 08:27 UTC, akx commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        return
This could use `match_from_list_with_error`?

2022-08-05 08:27 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        option = click.Option(
This isn't covered by tests? 🤔

2022-08-05 08:27 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                designated_endpoint, filename = key[1:].split('.')
No test coverage?

2022-08-05 08:27 UTC, akx commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        suggested_version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
What about without the `: str`?

2022-08-05 09:28 UTC, magdapoppins commented on valohai_cli/commands/deployment/create_version/create_version.py
> +        suggested_version_name: str = request('get', f'/api/v0/deployments/{deployment["id"]}/suggest_version_name/').json()['name']
Then it's upset about 
`valohai_cli/commands/deployment/create_version/create_version.py:65: error: Argument "version_name" to "CreationCommand" has incompatible type "Optional[str]"; expected "str"  [arg-type]`

2022-08-08 10:22 UTC, magdapoppins commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                'replicas': 1,
Agreed - I'm not sure how common setting these explicitly is but if needed, they can be added in a sequel of this pr.

2022-08-16 12:37 UTC, ruksi submitted a review, later dismissed
looking good!

added a few discussion points but all might be no-changes

2022-08-16 12:37 UTC, ruksi commented on tests/commands/run_test_utils.py
> +            re.compile(f'https://app.valohai.com/api/v0/deployments/{deployment_id}/suggest_version_name'),
unnecessary `re.compile`?

2022-08-16 12:37 UTC, ruksi commented on tests/commands/deployment/test_create_version.py
> +@pytest.mark.parametrize('name', (None, '666'))
very demonic

2022-08-16 12:37 UTC, ruksi commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                continue
wouldn't it make more sense to crash in error if the defined endpoint does not exist?

the situation that I'm imaging is that:
1. we have an automated script that releases a new deployment version on some trigger
2. it works now
3. somebody changes the endpoint names
4. the automated script still works as it skips the wrong names
    * as the script is automated, the warning simply gets logged somewhere in the ether
    * possibly even creates deployment versions with no endpoints enabled?
    
what do you think? do we see benefits in skipping incorrect definitions?

2022-08-18 10:20 UTC, magdapoppins commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +                continue
Sounds reasonable. Let's make it more obvious when things go wrong. 👍🏼

2022-08-22 10:34 UTC, akx requested changes
Some simplifications requested still (sorry!)

2022-08-22 10:34 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +            epilog='Multiple files per input: --my-input=myurl --my-input=myotherurl',
I still don't think you can do multiple files.

2022-08-22 10:34 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        endpoint_names_from_config = [e.name for e in self.config.endpoints.values()]
A set would be more correct here, but a minor nit really.
```suggestion
        endpoint_names_from_config = {e.name for e in self.config.endpoints.values()}
```

2022-08-22 10:34 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        self.endpoints = endpoints
Hmm... would it make things clearer to call this `endpoint_names`? I'm already confused with the strings and Endpoint objects here :)

2022-08-22 10:34 UTC, akx commented on valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> +        self.endpoints = endpoints
Or, would it make sense to make `self.endpoints` a mapping from enabled endpoint name to the Endpoint object?

```python
try:
    self.endpoints = {name: self.config.endpoints[name] for name in endpoint_names}
except KeyError as ke:
    raise KeyError(f"Endpoint not in configuration: {ke}")
```

or similar.

2022-09-08 10:46 UTC, akx approved these changes
:shipit:

2022-09-08 10:47 UTC, merged