Multiparam list
valohai/valohai-cli pull request #212
Opened 2022-09-13 06:37 UTC by tokkoro

Fixes #211

Multiple styled parameter will now be transferred as an array if such value. See more info in the issue #211.

2022-09-14 09:45 UTC, ruksi approved these changes
lgtm!

2022-09-14 09:45 UTC, ruksi commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            multiple=parameter.multiple is not None,
da beef :ok_hand:

2022-09-14 13:02 UTC, akx requested changes

2022-09-14 13:02 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            multiple=parameter.multiple is not None,
Should there be a test that shows how to use this in practice on the command line?

2022-09-15 05:49 UTC, tokkoro commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            multiple=parameter.multiple is not None,
Good idea, I also noticed that the help text says the single type for multiple type, so I will update that to say _multiple_ type**s**.

Current
```
- -
Parameter Options:
  --how-random FLOAT     How random you want the metadata to be
  --epochs INTEGER       How many epochs do you want?
  --wait-time FLOAT      How long to wait between generated metadata (seconds)
  --single-string TEXT
  --multi-separate TEXT
  --multi-repeat TEXT

  Multiple files per input: --my-input=myurl --my-input=myotherurl

```

2022-09-15 06:11 UTC, tokkoro commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            multiple=parameter.multiple is not None,
```
- -
Parameter Options:
  --how-random FLOAT     How random you want the metadata to be
  --epochs INTEGER       How many epochs do you want?
  --wait-time FLOAT      How long to wait between generated metadata (seconds)
  --single-string TEXT
  --multi-separate TEXT  (Multiple)
  --multi-repeat TEXT    (Multiple)

  Multiple styled parameters: --my-parameter=value1 --my-parameter=value2

  Multiple files per input: --my-input=myurl --my-input=myotherurl

```

2022-09-15 08:06 UTC, akx approved these changes

2022-09-15 08:06 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            help = "(Multiple) " + (help if help else "")
```suggestion
        help = (parameter.description or "")
        is_multiple = parameter.multiple is not None
        if is_multiple:
            help = f"(Multiple) {help}"
```
might be a bit more succinct...

2022-09-15 08:07 UTC, merged