Allow selecting an owner for the new project
valohai/valohai-cli pull request #219
Opened 2022-10-14 10:45 UTC by magdapoppins

Fixes #188

Some parts of this are copypasta from valohai-cli/commands/project/create.py, but I'm not sure how we could dry that out - the ownership prompt in that file requires a context for it to be used as a click param, so it's a bit tricky to pick it out from the Click.option class.

2022-10-14 10:53 UTC, akx requested changes
`OwnerOptionsOption` only only uses `ctx` for the `click.prompt` function's `value_proc`, which is optional anyway. IOW, you can refactor the meat of that class to a

```
def prompt_for_owner(*, value_proc=None) -> str:
```
and have `OwnerOptionsOption` call it as
```
return prompt_for_owner(value_proc=lambda x: self.process_value(ctx, x))
```
and use it without `value_proc` here.

2022-10-17 08:25 UTC, akx requested changes

2022-10-18 10:33 UTC, magdapoppins commented on valohai_cli/commands/project/create.py
> +    command_prompt: Optional[str] = 'Owner',
Apparently `click.Option`s `prompt` is `str | None` - that was the reason this originally optional.

2022-10-18 10:40 UTC, akx approved these changes

2022-10-18 10:40 UTC, merged