Pipeline parameters overriding
valohai/valohai-cli pull request #285
Opened 2023-08-18 10:53 UTC by memona008

Resolves #284  

## Why does this pull request exist?
To add overriding of pipeline parameters

## Changes made in this pull request:

- Override function added
- Test added

2023-08-21 05:45 UTC, ruksi commented
> Tests are being failed because it's not using latest valohai-yaml which returns parameters in convertedPipeline object

I guess we'll need to release new YAML version and/or upgrade dependency versions in the CLI before this can be rebased and merged  :+1:

2023-08-21 09:01 UTC, ruksi requested changes
freshly baked `valohai-yaml` in `master` so needs a rebase

also, one comment :P

2023-08-21 09:05 UTC, memona008 commented on valohai_cli/commands/pipeline/run/run.py
> +    return pipeline_parameters
The args list is like this ['--p1', '123', '--p2', '765'] 
so i am taking value starting with '--' as arg_name in one iteration and in next iteration I take its value. 
It can be improved by considering 2 indices at a time for name and value

2023-08-21 11:12 UTC, ruksi commented on valohai_cli/commands/pipeline/run/run.py
> +    return pipeline_parameters
this might also break if one of the pipeline parameters is a _flag_ as it doesn't have any value e.g. `--debug --epoh 300` :thinking: 

**but** I'm not sure if pipeline parameters even support flags elsewhere like normal steps do :stuck_out_tongue:

2023-08-21 11:17 UTC, memona008 commented on valohai_cli/commands/pipeline/run/run.py
> +    return pipeline_parameters
not a copy-paste I wrote it based on the args list
pipeline parameters do support flags. I have tested them. 
Let me cover all cases and re-push it. 😅

2023-08-22 12:54 UTC, ruksi approved these changes
could've added a suite of tests for the pipeline parameter styles you tried locally, presumably

but we can add those later :+1: 

maybe we could've used similar approach to `exec run` to use [`click` to do the argument parsing](https://github.com/valohai/valohai-cli/blob/master/valohai_cli/commands/execution/run/frontend_command.py#L135-L136) but that might require a more in-depth dive to `click` and its contexts, at least that is what I believe we are doing with executions :stuck_out_tongue: 

let's stamp this and go forward!

2023-08-22 12:54 UTC, merged