Kubernetes step parsing and command line options
valohai/valohai-cli pull request #298
Opened 2023-11-29 13:53 UTC by hylje

Included in this PR:
===

1. Parse Kubernetes `resource` structure from YAML when using `vh execution run`, if provided.
2. Parse Kubernetes resource claims directly as `vh execution run` command line arguments

`vh pipeline run` does not have execution runtime option override support for now.

2023-12-20 12:25 UTC, ruksi requested changes
lgtm, but a _question_

2023-12-20 12:25 UTC, ruksi commented on tests/commands/execution/test_run.py
> +            'containers': {
mixing of the `"` and `'` hurts my souls a bit but doesn't really matter :ghost:

2023-12-20 12:25 UTC, ruksi commented on tests/commands/execution/test_run.py
> +    }
the rest are not sent in the payload as we except that the API fills them from the YAML :+1:

2023-12-20 12:25 UTC, ruksi commented on tests/commands/execution/test_run.py
> +    }
not sure I understand this, why are the non-gpu resources sent in this case?

2023-12-20 13:15 UTC, hylje commented on tests/commands/execution/test_run.py
> +    }
Resources from YAML are parsed and sent if available (see the `run_test_setup_kube` fixture), and command line arguments can override them further. `--k8s-device-none` overrides just the devices dict into an explicit empty dict, while other resources are not overridden.

In the above partial case, the YAML doesn't define any resources so we won't send them either

2023-12-20 15:17 UTC, ruksi commented on tests/commands/execution/test_run.py
> +    }
but if we send YAML defined resources, wouldn't that mix up e.g. future copying? (we don't know know which of the passed parameters are API overrides vs. YAML overrides)

assuming that API doesn't compare passed resources to the YAML it knows 🤔

2023-12-20 15:24 UTC, ruksi commented on tests/commands/execution/test_run.py
> +    }
but I guess it's fine if it work like the wen UI, could double check it

2023-12-21 07:39 UTC, hylje commented on tests/commands/execution/test_run.py
> +    }
I don't think executions keep track of where the resulting configuration comes from, it's all put together and saved for later use. Copying doesn't refresh changes from yaml Steps, whether or not they were also supplied through the API or not.

I think the principle that front-end resolves the YAML itself and submits from it is alright, we already do it in CLI for parameters, inputs and environment variables.

I'm not against just leaving it for the API backend to work out, but I think that's its own project.

2023-12-21 08:04 UTC, ruksi commented on tests/commands/execution/test_run.py
> +    }
> I think the principle that front-end resolves the YAML itself and submits from it is alright

yeah, I also feel that it's all-OK :+1: 

> I'm not against just leaving it for the API backend to work out, but I think that's its own project

yeah, definitely a separate thing if we feel that it's needed

2023-12-21 08:29 UTC, ruksi approved these changes
is good

2023-12-21 08:29 UTC, merged