option to disable git packaging for adhoc execution
valohai/valohai-cli pull request #313
Opened 2024-08-29 08:36 UTC by Kenneth-Schroeder

should resolve #122

2024-08-29 12:52 UTC, akx requested changes
Thanks!

I think a positive argument that's set to `true` by default, and can be disabled with a negative flag, would be more intuitive.

NB: I didn't test the suggestions locally, so they might be wrong :)

2024-08-29 12:52 UTC, akx commented on valohai_cli/commands/pipeline/run/run.py
> +    commit = create_or_resolve_commit(project, commit=commit, adhoc=adhoc, yaml_path=yaml, allow_git_packaging=not disable_git_packaging)
```suggestion
    commit = create_or_resolve_commit(project, commit=commit, adhoc=adhoc, yaml_path=yaml, allow_git_packaging=git_packaging)
```

2024-08-30 10:54 UTC, Kenneth-Schroeder commented
Thank you, good feedback, I am not familiar with click :)

2024-08-30 11:40 UTC, teroyks approved these changes
LGTM, and the test agrees.

2024-08-30 11:40 UTC, merged