Add SSH command for executions
valohai/valohai-cli pull request #314
Opened 2024-08-31 13:51 UTC by memona008

User will be able to remotely debug the execution 
1. He can either provide address:port & private key by himself or run the command for auto collection of the details
2. If the key is generated in CLI while starting the execution it can be found by command and prompted to user as option 
3. But if the execution is started by UI or key is generated somewhere user HAS to provide that key as command argument `--private-key-file `

2024-08-31 16:21 UTC, tarekoraby commented
Does this resolve #312?

I assume this is the final piece of [#7172](https://github.com/valohai/roi/issues/7172). If so, please share a screenshot or a recording of the typical steps the end user will experience after merging this PR.

2024-09-02 05:46 UTC, akx requested changes

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +def get_default_ssh_folder() -> str:
We've used the term `directory` before, let's use it here too.

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +    return os.path.join(home_dir, ".ssh")
```suggestion
    return os.path.expanduser("~/.ssh")
```

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        return None
Use `valohai_cli.utils.cli_utils.prompt_from_list()` instead :)

2024-09-02 05:46 UTC, akx commented on valohai_cli/log_manager.py
> +        }
* I'm not sure this should be in `LogManager`, since it doesn't touch `LogManager`'s state (seen messages) at all. It should probably just be a free function.
* Since `total` from the dict isn't used at all, this should maybe just return an `Iterable[dict]`, i.e. `yield from events_response.get('status_events', ())`.

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        return
This would cause the command to finish with exit code 0 (success).

Raise a `click.UsageError()` instead.

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +    return None
* I think this should try to parse the `::ssh::` dict into either a tuple (host, port) or a `dataclass` designed for that purpose.
* The `prefix` doesn't IMO need to be configurable – how would we find SSH details from a non-`::ssh::` message?

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +    click.echo(NO_KEY_FOUND_MESSAGE)
This too should be an error condition, not just an echo.

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +@click.option('--address', default=None, help='Container IP address to connect to.')
The help text should specify the format required (looking at the code, it's "address:port", not just an IP address).

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        }
```suggestion
        ip_address, _, port = address.partition(":")
        ssh_details = {
            "address": ip_address,
            "port": int(port),
        }
```

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        }
Feels like the entire "get project, get execution, parse SSH details" bit should be moved to a free helper function.

Then we wouldn't even need to retrieve the project and execution at all if the user already provided an address to SSH to.

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +                return
Feels like there should be only one call to `make_ssh_connection_to_container()` in this function 🤔

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        ]
🤔 😄 

```suggestion
```

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +                return
* The `for folder ... find key...` loop should probably also be in `utils/ssh.py`.
* We should probably find all keypairs in all of the given directories, and prompt the user only once. Otherwise, it's a bit silly that you get two "do you want to use this key?" prompts..?

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        click.echo("SSH command not found. Ensure SSH is installed and available in your PATH.", err=True)
Maybe use `shutil.which()` to find `ssh` and raise if it returns None. (Otherwise, use the return value in the subprocess command.)

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        click.echo(f"An unexpected error occurred: {ex}", err=True)
We shouldn't be catching these, I don't think?

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +            raise ValueError("Missing necessary SSH connection information.")
Doesn't the caller validate all of these?

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +def make_ssh_connection_to_container(address: str, port: str, private_key_path: str) -> None:
`port` should be an integer.

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        click.echo(result.stdout)
I don't think this is what we want if we want to start an interactive SSH session...

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +def get_ssh_key_pairs_from_dir(folder_path: str) -> tuple:
* This too should probably return a generator of some `Keypair` dataclass, to avoid `key_pairs[0][0]`.
* `directory` instead of `folder`

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        return False, []
Since we kind of always need the public part to be around (to eventually send with the execution configuration), I think we could just try to find `.pub`s, then assume they'll be paired with a suffixless private key part. Also, let's not support `ssh-dss` keys, they're deprecated.

Something like:

```suggestion
    for pth in pathlib.Path(folder_path).glob("*.pub"):
        if not pth.is_file():
            continue
        try:
            with pth.open("rb") as f:
                if not first_line.startswith((b"ssh-rsa", b"ecdsa-sha2-", b"ssh-ed25519")):
                    continue
            priv_pth = pth.with_suffix("")
            if priv_pth.is_file():
                yield Keypair(public_path=pth, private_path=priv_pth)
        except OSError:  # e.g. unreadable key
            pass
```

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +        return None
I think the caller should validate it passes in a proper directory.

2024-09-02 05:46 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +DEFAULT_SSH_DIR = get_default_ssh_folder()
I don't think this needs to be a module-level constant here.

2024-09-02 05:46 UTC, akx commented on valohai_cli/utils/ssh.py
> +CLI_CONFIG_DIR = get_settings_root_path() + "valohai-cli/"
I think this statement should just use `get_settings_file_name()` so it knows about `VALOHAI_CONFIG_DIR`. 

In `get_settings_file_name()`'s docstring, we should maybe clarify that it's OK to e.g. pass in an empty string for `name`...

Finally, I don't think this needs to be a module-level constant either, if it'll only get used eventually in the "find some SSH key" loop.

2024-09-02 06:18 UTC, memona008 commented
> If so, please share a screenshot or a recording of the typical steps the end user will experience after merging this PR.

Thanks for the reminder. I'll do it once all the comments are addressed and PR is in its final shape so that our CS would get the latest and final recording/screenshot/steps.

2024-09-02 06:21 UTC, memona008 commented on valohai_cli/utils/ssh.py
> +        ]
aaahh noooooo waayy i pushed the testing details *dying with embarassment*

2024-09-02 12:48 UTC, akx requested changes

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +        ssh: Optional[bool] = False,
`Optional[bool]` implies `None` is an option here. Is it?

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +            time.sleep(10)
This seems awfully arbitrary. If the idea is to wait until we might be able to see the SSH details, the `ssh` command should instead have an option to loop until it finds the SSH details.

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +        if self.ssh:
Since the `ssh` command will block the terminal (interactive SSH session and all), this should occur after the `open_browser` `if`, so you can open a browser, then wait for SSH. Otherwise you'd get an SSH session, and after you ctrl+c out of it, a browser would pop up.

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/frontend_command.py
> +    ssh: Optional[bool] = False,
`ssh`, `sync` and `watch` are mutually exclusive (all of them are blocking processes), please make it so :)

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/frontend_command.py
> +    ssh: Optional[bool] = False,
I doubt `None` is an option here:
```suggestion
    ssh: bool = False,
```

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +    help='Address of the container in "ip:port" format.If not provided, '
```suggestion
    help='Address of the container in "ip:port" format. If not provided, '
```

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +        return f"Keypair(public_path={self.public_path}, private_path={self.private_path})"
[Dataclasses auto-generate these for you.](https://docs.python.org/3.12/library/dataclasses.html#module-dataclasses)

```suggestion
    public_path: pathlib.Path
    private_path: pathlib.Path
```

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +@dataclass
Might as well make it immutable:
```suggestion
@dataclass(frozen=True)
```

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +            )
This can be outside the `try:` block.

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +            click.echo(f"Error details: {e.stderr}", err=True)
I don't think this is (easily) reachable (and the `stderr` bit especially isn't, since you're not capturing `stderr`). I'm not sure there's much value in the whole `try:except:` here; the user would see the error from `ssh`, wouldn't they?

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +        click.echo(f"Looking for private key in {dir}...")
Is this verbosity necessary? Maybe we should print the directories only if we didn't find any keys.

2024-09-02 12:48 UTC, akx commented on valohai_cli/utils/ssh.py
> +    ssh_details = find_ssh_details(list(events_response))
```suggestion
    ssh_details = find_ssh_details(fetch_status_events(execution, first_n=100))
```
(and make the argument type accepted by `find_ssh_details` an `Iterable`)

2024-09-02 12:48 UTC, akx commented on valohai_cli/commands/execution/run/dynamic_run_command.py
> +        :param ssh: Whether opens an interactive ssh connection for debugging
```suggestion
        :param ssh: Whether to chain to `exec ssh` afterward
```
(to copy the documentation for `watch`)

2024-09-04 07:31 UTC, akx requested changes

2024-09-04 07:31 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        raise click.Abort()
What's the benefit of having everything wrapped in a try/except here? 🤔 Since `CLIException`s derive from `click.ClickException`, they'll be handled nicely anyway (see https://click.palletsprojects.com/en/8.1.x/exceptions/).

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +    delay_range: Tuple[int, int] = (1, 7),
Since you never pass these in to `get_ssh_details_with_retry`, they maybe don't need to be arguments to this function.

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/__init__.py
> +    raise exception(f"Failed after {retries} retries")
* We don't need `args` and `kwargs` here; `func` itself could be a `lambda` or `functools.partial()`.
* We could want to catch multiple exception classes (e.g. `(IOError, TimeoutError)`)
* `raise exception` is a bit weird – you can't necessarily be certain that any given exception type passed in by the user is constructible with a string. It would also be useful to be able to access the exception.

Maybe something like:

```suggestion
T = TypeVar("T")


def call_with_retry(
    func: Callable[[], T],
    retries: int = 3,
    delay_range: Tuple[int, int] = (1, 5),
    retry_on_exception_classes: Tuple[Type[Exception], ...] = (Exception,),
) -> T:
    for attempt in range(retries):
        try:
            return func()
        except retry_on_exception_classes as e:
            if attempt == retries - 1:
                raise RuntimeError(f"Failed after {retries} attempts") from e
            click.echo(f"{attempt + 1}/{retries} Retrying: {e}...")
            time.sleep(random.uniform(*delay_range))
```

2024-09-04 07:31 UTC, akx commented on valohai_cli/commands/execution/run/frontend_command.py
> +    ssh: bool = False,
As said in the last review:

> ssh, sync and watch are mutually exclusive (all of them are blocking processes), please make it so :)

There is also precedent for 2 mutually exclusive options (see `if download_directory and watch:`).

2024-09-04 07:31 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +@click.option("--private-key-file", default=None, help="Private SSH key to use for the connection.")
```suggestion
@click.option("--private-key-file", default=None, type=click.Path(file_okay=True, exists=True), help="Private SSH key to use for the connection.")
```
and you don't need to validate the existence of the file by hand.

2024-09-04 07:31 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +            raise click.UsageError(f"No such key file found: {private_key_file}")
```suggestion
```
✂️ if you use `click.Path()`.

2024-09-04 07:31 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        click.echo(f"SSH Container address is {ip_address}:{port}")
"SSH Container address"? 🤔 Sounds like there is a separate container?

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +def make_ssh_connection_to_container(address: str, port: int, private_key_path: str) -> None:
I don't think there's much value in saying `_to_container` here?
```suggestion
def make_ssh_connection(address: str, port: int, private_key_path: str) -> None:
```

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +    return os.path.expanduser("~/.ssh")
This probably could be inlined into the single function that uses it now.

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +        if not os.path.exists(dir):
```suggestion
        if not os.path.isdir(dir):
```

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +            all_keypairs.extend(key_pairs)
It's a generator, you don't need to check before extending.

```suggestion
        all_keypairs.extend(get_ssh_key_pairs_from_dir(dir))
```

2024-09-04 07:31 UTC, akx commented on valohai_cli/utils/ssh.py
> +        args=(counter,),
As discussed around simplifying `call_with_retry`,
```suggestion
        func=partial(get_ssh_details_from_execution, counter=counter),
```
or
```suggestion
        func=lambda: get_ssh_details_from_execution(counter),
```

2024-09-04 10:51 UTC, akx requested changes

2024-09-04 10:51 UTC, akx commented on valohai_cli/models/project.py
> +        raise_on_not_running: bool = False,
I don't think this functionality belongs in `get_execution_from_counter()`.

You could have a ssh.py-specific function that `get_execution_from_counter()`s and raises on a given status type, but also see the commentary in that module.

2024-09-04 10:51 UTC, akx commented on valohai_cli/models/project.py
> +            if raise_on_not_running and data["status"] == "queued":
So the new parameter doesn't do what it's named to do? Based on this it'd be `raise_if_queued`?

Either way, for the "wait until it's up and running" functionality for SSH you really would also want to raise if the execution has e.g. stopped or errored already.

2024-09-04 10:51 UTC, akx commented on valohai_cli/models/project.py
> +                    f"Execution #{counter} is not running. It's current status is: {data['status']}",
Typo: `it's` -> `its`.
```suggestion
                    f"Execution #{counter} is not running. Its current status is: {data['status']}",
```

Also, you're ensuring `status` is queued above, so there's no way this could ever be "Its current status is: queued"...

2024-09-04 10:51 UTC, akx commented on valohai_cli/utils/ssh.py
> +    Fetch SSH details for a given execution, retrying up to `retries` times with a random delay between retries.
The docstring is referring to now-deleted arguments...
```suggestion
    Fetch SSH details for a given execution.
```

2024-09-04 10:51 UTC, akx commented on valohai_cli/utils/ssh.py
> +    return execution
I don't think this needs to be a "public" function if it only is ever called by `get_ssh_details_with_retry`.

Also, I'm not sure `call_with_retry()` is a great idea for waiting for the execution to become `started` – you'd be waiting for 5 to 35 seconds, and then giving up altogether.

I think it'd be better to:

* loop forever until the execution becomes `started` (and error out if it's e.g. stopped or errored; we can't SSH there)
  * maybe 5 seconds between retries?
  * print out a "Waiting for execution to start" after the first few tries and thereafter every now and then
  * the user can always ctrl+c out of this
* then in a subsequent loop or retry-loop, find the SSH events.

2024-09-04 10:51 UTC, akx commented on valohai_cli/commands/execution/ssh.py
> +        make_ssh_connection(ip_address, port, selected_private_key)
I think this reads more clearly as
```suggestion
    if not private_key_file:
        private_key_file = select_private_key_from_possible_directories()
    make_ssh_connection(ip_address, port, private_key_file)
```

2024-09-04 10:51 UTC, akx commented on valohai_cli/utils/ssh.py
> +def select_private_key_from_possible_directories() -> Optional[str]:
Isn't the rtype always `str`? This either raises or returns a string.
```suggestion
def select_private_key_from_possible_directories() -> str:
```

2024-09-04 13:55 UTC, akx requested changes
Still a bit to go, sorry...

2024-09-04 13:55 UTC, akx commented on valohai_cli/utils/ssh.py
> +    if execution["status"] in ("stopped", "stopping (hard)", "stopping", "error", "complete"):
The `status` from the API will not be `"stopping (hard)"`, it will be `"stopping_hard"`...

2024-09-04 13:55 UTC, akx commented on valohai_cli/exceptions.py
> +    color = "yellow"
Since these are only used by the `ssh` machinery, and only internally therein, I don't think they should be here. (But see more comments in the `ssh.py` module, I don't think these are really necessary at all...)

2024-09-04 13:55 UTC, akx commented on valohai_cli/utils/ssh.py
> +            raise
I would inline `_get_execution_from_counter()` here and avoid the extra exception classes. `count()` is from `itertools`.

```suggestion
    project = get_project(require=True)
    assert project

    for attempt in count():
        execution = project.get_execution_from_counter(
            counter=counter,
            params={"exclude": "metadata, events"},
        )
        if execution["status"] in ("queued", "created"):
            if attempt % 3 == 0:  # print on first attempt and thereafter every 3 attempts
                click.echo(f"Execution #{counter} is {execution['status']}. Waiting for it to start...")
            time.sleep(5)
            continue
        if execution["status"] != "started":
            raise CLIException(f"Execution #{counter} is {execution['status']}. Cannot SSH into it.")
```

2024-09-06 07:03 UTC, akx requested changes
Looks good, but could we have some tests for this?

2024-09-10 12:15 UTC, akx requested changes

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +    EXECUTION_DATA["status"] = "started"
Ditto about modifying `EXECUTION_DATA`.

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +    EXECUTION_DATA["status"] = "started"
Ditto about modifying `EXECUTION_DATA`.

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +from tests.commands.execution.test_watch import no_sleep
Shouldn't this import from `utils` (since you move it there)?

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +    monkeypatch.setattr(time, "sleep", no_sleep)
Hmm... `no_sleep` always raises a KeyboardInterrupt (i.e. as if the user had interrupted the sleep immediately).

What is it that we're testing here?

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +    monkeypatch.setattr(time, "sleep", lambda x: None)
Why does `sleep` need to be mocked here? 🤔

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +        return pathlib.Path("/path/to/private")
Add the `tmp_path` fixture to the test and return that instead of hard-coding a path:
```suggestion
    def mock_prompt():
        return tmp_path
```

2024-09-10 12:15 UTC, akx commented on tests/fixture_data.py
> +}
This seems specific to the SSH tests – maybe do like `test_execution_outputs` does and modify the mock `with get_execution_data_mock() as m:` to only return these when they should be present? That would also make `test_ssh_with_no_ssh_details_present` test more actual behavior, as you wouldn't need to mock `find_ssh_details` to a no-op.

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +        monkeypatch.setattr("valohai_cli.commands.execution.ssh.make_ssh_connection", mock_ssh_connection)
Maybe monkeypatch `subprocess.run` instead with a mock, and check that the mock gets called with the correct command line?

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +        assert "SSH address is 127.0.0.1:2222" in output
I'm not following why this test does two invocations..?

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +        assert f"Error: Execution #{counter} is complete. Cannot SSH into it.\n" in output
I wouldn't personally test against the full error message, newline and all, but it's okay.

2024-09-10 12:15 UTC, akx commented on tests/commands/execution/test_ssh.py
> +
Please assert that `output.exit_code` is the expected non-zero status (consider this repeated for all of these error tests).

2024-09-12 06:05 UTC, akx commented on tests/commands/execution/test_ssh.py
> +    monkeypatch.setattr(time, "sleep", lambda x: None)
Why would it wait for 5 seconds somewhere to begin with? I thought we only sleep when retrying?

2024-09-12 08:09 UTC, memona008 commented on tests/commands/execution/test_ssh.py
> +    monkeypatch.setattr(time, "sleep", lambda x: None)
Oh yes, i added it in the failing scenerios to avoid waiting 
it doesnt make sense here in all-good-flow so removing it 👍🏼

2024-09-12 10:21 UTC, akx approved these changes
Thanks for putting up with all of the review comments, I think we ended up with a pretty elegant solution :)

2024-09-12 10:21 UTC, merged